### ISSUE TITLE
Where did the Eden World Builder Repository go? 

### ISSUE THREAD

**Issue by SeaFish937** [ryanjkontos/HLL-Old#2]

**Comment by ryanjkontos** [comment]
Hi! The Eden World Builder code is not mine, but the original creator did release it a few years ago at a point where he basically said “here, I don’t care about it anymore, have it”. As a result I don’t think I really have any authority to set a license. That being said, I’m pretty sure the whole thing is abandoned so as long as you don’t try to sell a clone on the App Store, messing with the code should be fine. I’ve just made the repo public on this account. :)

**Comment by ryanjkontos** [comment]
Also, if you do happen to make any updates please let me know. I’d love to have a version running full screen on modern iOS devices sizes on day, but the app is from a time where there were only like, 3 device sizes and so  everything is hardcoded. Would take a significant rewrite to fix that.

**Comment by user624264835** [comment]
I am impressed to see that you responded so quickly! And thanks for responding I am glad that developers are still alive.

**Comment by user624264835** [comment]
Are there any other ways I could get in contact with whoever was in charge of the project previously? I think it was someone named Ari? And yeah I agree, I'd love to see some updates to Eden World Builder! Its been way to long and I think that this game really needs a revival. Ideally, the game could also work on all major operating systems (Linux+GNU, Mac OSX, Android and iOS Windows etc.) And yes, higher resolutions would also be a nice touch.

**Comment by user624264835** [comment]
"This project is licensed under the GNU General Public License v3 - see the [LICENSE.md](https://github.com/ryanjkontos/EdenWorldBuilder/blob/master/LICENSE.md) file for details" This does not currently exist, or is private. (https://github.com/ryanjkontos/EdenWorldBuilder#readme) I am also curious as to why the project became private.

**Comment by ryanjkontos** [comment]
Yeah that’s correct. Are you remembering that from the old Facebook group?

Ari used to be fairly active on the Eden Discord server. For a while he was committed to releasing an update to the game and he actually _did_ a few months ago. It’s available on the app store as a new purchase called “Eden New Dawn”. It does fix a few bugs, like the glitchy/old UI which shows up when you open the app on newer iPhones. But it’s still pretty glitchy and buggy, doesn’t seem like much effort went into it tbh. 

Anyway I haven’t really been keeping up with the server in a few years but from what I can gather, after releasing that update Ari announced that he was giving up again and actually left the server, so now there’s not really any way of contacting him. I doubt anything substantial will ever really come of Eden again. Its codebase is a decade-old mess that I don’t think anyone experienced enough will really ever have the time or motivation to bother fixing. There have also been a bunch of attempts on the discord by people to write the game in unity or whatever, but they’re never ended up going anywhere.

As to why I made the repo private, I don’t really remember? I think I was just not comfortable hosting the code when I had nothing to do with it. Now I don’t really care lol.

**Comment by user624264835** [comment]
If you don't mind me asking, what did you do when you worked on Eden World Builder? (I assume you did because you are currently hosting the source code.)
